# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: npm
    directory: /server
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      server-production:
        dependency-type: production
      server-development:
        dependency-type: development

  - package-ecosystem: npm
    directory: /mobile
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      mobile-production:
        dependency-type: production
      mobile-development:
        dependency-type: development

  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      web-development:
        dependency-type: development
